// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHN31_AJxOD2z9LzWZ8i9UgVsBoL3ftE',
    appId: '1:104216248112:web:4b9561dbcb7bc226f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    authDomain: 'dwa2y-3cb9f.firebaseapp.com',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUhNhAlTVL6DjXYrSuaHAQLW1ftm1h1U',
    appId: '1:104216248112:android:18251dc833a0bd58f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1YKhbZT2hF7pyt5vOytupR8t3zNa_NQ',
    appId: '1:104216248112:ios:6ed5bc707f7152c6f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
    androidClientId: '104216248112-aemfpouq12hfuaerrfdr4o913bsq0g8m.apps.googleusercontent.com',
    iosClientId: '104216248112-jssc2a4rt8k8mtqgp0omld64nm8n0mo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2yPharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1YKhbZT2hF7pyt5vOytupR8t3zNa_NQ',
    appId: '1:104216248112:ios:6ed5bc707f7152c6f6d2f5',
    messagingSenderId: '104216248112',
    projectId: 'dwa2y-3cb9f',
    storageBucket: 'dwa2y-3cb9f.appspot.com',
    androidClientId: '104216248112-aemfpouq12hfuaerrfdr4o913bsq0g8m.apps.googleusercontent.com',
    iosClientId: '104216248112-jssc2a4rt8k8mtqgp0omld64nm8n0mo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwa2yPharmacy',
  );
}
