import 'package:get/get.dart';

class Languages extends Translations{

  @override
  Map<String, Map<String, String>> get keys =>{
      'ar':{
        //app name
                "3lagy":"علاجي",
          "Pharmacy App":"وصل أدويتك بأسرع وقت",
        //login and sign up
        "sign in":"تسجيل الدخول",
        "sign up":"إنشاء حساب",
        "email":"بريد إلكتروني",
        "password":"كلمه السر ",
        "register":"إنشاء حساب",
        "Get Medicine":"علاجك في جيبك",
        "Don't Have Account?":"ليس لديك حساب ؟",
        "Forgot Password?":"نسيت كلمه السر ؟",
        "username":"أسم المستخدم",
        "confirmpassword":"تأكيد كلمه السر",
        "passwords don't match":"كلمه السر ليست متطابقه",
        "phone":"رقم الهاتف",
        "login":"تسجيل الدخول",
        "Already Have an Account?":"لديك حساب بالفعل؟",
        "CreateAccount":"إنشاء حساب جديد",
        "Please Enter correct Username":"أدخل اسم مستخدم",
        "Please enter correct password":"أدخل كلمه سر صحيحه",
        "please enter Email":"أدخل بريد الكتروني",
        "Hello,":"مرحبا",
        "How do you feel today?":"كيف حالك اليوم ؟",
        "Find pharmacy":"أبحث عن صيدليه",
        "Order via Prescripton":"صور الروشتة",
        "Place an order":"طلب كتابي ",
        "Your Pills for today":"تذكير الأدويه",
        "Add Reminder":"طلب تذكير",

        //my account
        "MyAccount":"حسابي",
        "Orders":"طلباتي",
        "Near Pharmacies":"الصيدليات القريبة",
        "Home ":"الرئيسيه",
        
        "Personal Information":"معلوماتي",
        "Payment methods":"طرق الدفع",
        "Account Setting":"بيــانات الحــساب",
        "Billing Address":"عناويني",
        "Help and Support":"طلب مساعده",
        "Logout":"تسجيل خروج",
        "Languages":"مثل اللغه",
        "Personal Data":"بيانات شخصيه",
           "Name":"الأسم",
        "Gender":"النوع",
        "Birthday":"تاريخ الميلاد",
        "Confirm":"تأكيد",
        "Cancel":"إلغاء",
        "Tap to Set":"تعديل",
        "alert":"تنويه",
         "Select Gender":"أختار النوع",
        "Male":"ذكر",
        "Female":"أنثي",
        "Save":"حفظ",
        "Default Language":"اللغه الأساسية",
         "My Address":"عناويني",
        "Work":"العمل",
        "Delete":"حذف",
        "Edit":"تعديل",
        "Street Name":"شارع",
        "floor":"الدور",
        "Apartment Number":"شقه رقم",
        "Add A New Address":"إضافة عنوان جديد",
        "Default":"الأساسي",
     "Long Press":"أضغط طويلا",
        "Long Press On Address to Change Default Address":"أضغط علي العنوان لمده لكي تستطيع تغيير العنوان الأساسي ",
        "Changed Address":"تغيير العنوان الأساسي",
        "Changed Default Address to":"تم تغيير العنوان الأساسي الي ",
        "Nearby Pharmacies":"الصيدليات القريبة",
        "Distance":"المسافه ",
        "KM":"كيلومتر",
        "Deliver to ,":"  توصيل إلي  , ",
              "Pending":"قيد الأنتظار",
      "Completed":"مكتمله",
      "Waiting For Delivery":"يتم الان التوصيل",
      "Delivered":"تم التوصيل",
      "Pharmacy :":"صيدلية :",
      "Try to create New orders":"أبدا بطلب أدويتك الأن",
         "Delete Orders":"حذف الطلبات",
      "Are you sure to delete":"هل تريد حذف الطلبات",
      "Yes":"نعم",
      "No":"إالغاء",
      "?":"؟",
       "Rejected":"تم رفض الطلب",
      "Delivering":"يتم الأن التوصيل",
      "Medicine":"الدواء",
      "Price":"السعر",
      "Order Date":"تاريخ الطلب",
    "Order Details":"حاله الطلب",
    "All Pharmacies Rejected Your Order":"جميع الصيدليات رفضت الطلب ",
    "still didn't find pharmacy just wait !":"في انتظار قبول طلبك من الصيدليات",
    "Pharmacy is delivering your order to you":"يتم الان توصيل الطلب من قبل الصيدليه",
    "your order has successfully delivered":"تم توصيل الطلب بنجاح ",
    //upload prescription page
    "Upload Prescription":"إرفاق الروشتة",
    "Change":"تغيير",
    "Add Photos":" إضافة الروشتة ( أضغط هنا )",
    "Continue":"إســتكمال",
        "Change Address":"تغيير العنوان",
    "Tap Here To Change Your Address":"أضغط هنا لتغيير العنوان ",
    "Select Address to deliver":"أختر عنوان لك قبل الطلب ",
    "Select":"أختر",
    "Choose From":"أختر من",
      "Gallery":"المعرض",
     "Camera":"الكاميرا",
       "Add Prescriptions":"إرفاق الروشتة",
     "Click Here To Attach Prescriptions ":"أضغط هنا لكي ترفق الروشته في الطلب ",
     "No Pharmacies yet!!":"لا يوجد صيدليات حتي الأن",

     "Choose Pharmacies":"أختر الصيدليات",
     "Pick Distance to Show Pharmacies,":"أختار المحيط المطلوب لتظهر الصيدليات في نطاق ",
     "Send to":"إرسال إلي",
     "Pharmacies":"صيدليات",
     "No Pharmacies registered in this area try to scale KM":"لا يوجد صيدليات متاحه في هذا النطاق حاول توسعه النطاق",
       //Account Setting Screen
     "Change Language":"تغيير اللغه ",
     "Change Default App Language":"تغيير اللغه الأساسية",
     //snackbars
       "Error":"خطأ",
     "Please type in medicine":"من فضلك اكتب الدواء المطلوب ",
     "add pharmacies":"أضف صيدليات",
     "Please pick some Pharmacies":"من فضلك أختر صيدليات",
    "Sending Notification...":"... جاري إرسال الطلب",
    "Pharmacy Order Rejected":"تم رفض الطلب ",
   
    "Rejected your Order":"رفض طلبك ",
    "Rejected Your Offer":"رفض العرض المقدم منك ",
       "Order Accepted":"تم قبول طلبك",
    "offers you":"يعرض عليك",
    "Tab To See":"أضغط لتري العرض",
    "New Offer For Your Order":"عرض جديد لديك",
    "Loading...":"... تحميل ",
     "Too Late":"متأخر جدا",
      "Customer Accepted Another Pharmacy Offer":"العميل وافق علي عرض سعر من صيدليه أخري ",
      "Pharmacy Offer":"عرض من صيدليه ",
      "Great":"ممتاز",
      "Succssefully Added Product":"تم أضافه منتج جديد",
      "fill fields":"أملأ الفراغات",
      "Please Fill All Required Fields":"من فضلك املأ الخانات الفارغة",

     //address
     "Additional Address Details":"معلومات أخري عن العنوان ",
     "Address Label (Optional)":"نوع العنوان ",
     "Home":"المنزل",
  "SAVE ADDRESS":"حفظ العنوان",
 "Near to":"بجوار (مكان مميز)",
 "Delete Address":"حذف العنوان",
  "Are you sure you want to delete this address":"هل تريد حذف العنوان ؟",

  //
  "Prescription":"روشته",
  "New Reminder":"تذكير جديد",
  "Medicine Name":"أسم الدواء",
   "Type":"النوع",
   " Time & Schedule ":"الوقت والتاريخ",
   "Duration":"المده",
   "Once":"مره واحده",
   "Repeated":"متكرر",
   " Repeat Every ":"تكرار كل",
   "Type All Fields":"أدخل كل الخانات",
   "Please Fill in All Fields":"من فضلك أدخل كل الخانات",
   "Add A Reminder":"أضف تذكير",
   "Try to Add your Default Address For Delivery":"حاول ان تضع علي الاقل عنوان ",
     //orders notification
  "New Order For You":"طلب جديد لك ",
    "Offer him a price":"أعرض عليه سعر",
  "Accept":"موافق",
  "Reject":"رفض",
  "Customer Name:":"أسم العميل :",
  "accepted your offer":"وافق علي العرض ",
  "Please Offer Him price for Prescription":"من فضلك أعرض عليه سعر ",
  "Offer Accepted":"تم قبول عرضك ",
  //permission
  "GPS permission Request":"أذن الحصول علي ال GPS",
  "Location permission is Required for better using of app":"من فضلك قم بتفيل ال gps ",
  "Turn On Gps":"قم بتشغيل ال gps",
  "Please Enable Gps And try Again...":"قم بتشغيل الجي بي أس وحاول مره أخري",
  "Ok":"موافق",
"GPS Error":"خطأ في الجي بي أس",
  //notification page
  "Notifications":"إشعارات",
  "Order Number:":" رقم الطلب : ",
  " NOTE :":" ملاحظه: ",
  "Give him a Call":"أتصل به الأن",
  "Start Chat with him":"ابدأ محادثه الأن",
  "View Order Details":"شاهد الاوردر المطلوب",
  "Order Request":"طلب دواء",
  "Tap To View":"اضغط لتري الطلب ",
    "Offer Rejected":"تم رفض العرض",
  "Accepted Your Offer Deliver it now!!":"وافق علي عرضك سارع بتوصيل الأوردر الأن",
  //order from pharmacy
  "Make Order":"طلب دواء",
  "click on (Add Photos) to add Some Prescriptions of your medicine":"أضغط علي (إضافة الروشتة ) لكي ترفق الروشته الخاصه بك",
  "Please provide prescription photos or type in required medicine":"من فضلك اكتب الدواء المطلوب في الخانه الفارغه",
  "Address Is Empty":"لم تقم بأختيار عنوان ",
  "Please add at least one Address":"من فضلك أضف عنوان لكي يتم توصيل الطلب",
   "Submit":"أطلب الأن",
   "Tap to Accept or refuse":"أضغط للتفاصيل",

      //google map page
   "Locate Me":"موقعي الأن",
   "CONFIRM LOCATION":"تأكيد المكان",

   //pharmacy details
   "Pharmacy Details":"معلومات عن الصيدليه",
   "Nearby":"بجوار",
   "Address":"العنوان",
   "Order Medicine":"طلب دواء",
   "Pharmacy Products":"منتجات الصيدليه",
     //products
     "My Products":"منتجاتي",
  "Add Product":"إضافه منتج",
  "Add Product Image":"إضافه صوره المنتج",
  "Product Name":"أسم المنتج",
  "Product Price":"سعر المنتج",
  "Product Category":"نوع المنتج",
  "Capsules":"كبسولات",
  "Syurp":"شراب",
  "Other":"أخري",
  "Baby":"أطفال",
  "Cosmatics":"تجميل",
  "Discount Percentage (Optional)":"نسبه الخصم (اختياري )",
  "Edit Product":"تعديل المنتج",
  "Edit Price":"تعديل السعر",
  "See All":"الكل",
   //PharmacyProducts
  "Products":"المنتجات",
  "All":"الكل",
  "Please Add More Products":"أضف منتجات جديده",
  "Tap to View Details":"أضغط للتفاصيل ",
  "Try to Get Some Orders":"حاول الحصول علي طلبات من العملاء",
  
  "Pharmacy don't have any products till yet!!":"لا يوجد منتجات في الوقت الحالي",

  //shopping cart 
  "Cart":"العربة",
  "Item":"منتج",
  "Product Name: ":": أسم المنتج ",
  "Category: ":":النوع ",
  "L.E":"جنيه",
  "CHECKOUT":"الدفع",
  "Your Shopping Cart Is Empty":"العربة ليس بها أي منتج حاليا",
  "Update":"تحديث",
  //order detail
  "Order Status :":"حالة الطلب : ",
          "Payment Method :":"طريقة الدفع : ",
          "Price :":"السعر :",
"Set to Delivered":"تم توصيل الاوردر",
"In Cash":"نقدا",

      },



      'en':{
        "3lagy":"3lagy",
        "Pharmacy App":"Deliver Medicine",
         "sign in":"Sign In To 3lagy",
         "Get Medicine":"Get Your Medicine quickly ,,",
         "sign up":"Sign Up",
         "email":"Email",
         "password":"Password",
         "register":"Register Now",
         "Don't Have Account?":"Don't Have Account",
         "Forgot Password?":"Forgot Password?",
         "username":"username",
         "confirmpassword":"ConfirmPassword",
          "passwords don't match": "passwords don't match",
         "phone":"Phone",
         "login":"Login",
         "Already Have an Account?":"Already Have an Account?",
         "Create Account":"Create Account",
         "Please Enter correct Username":"Please Enter correct Username",
         "Please enter correct password":"Please enter correct password",
         "please enter Email":"please enter Email",
         "Hello,":"Hello,",
         "How do you feel today?":"How do you feel today?",
         "Find pharmacy":"Find pharmacy",
         "Order via Prescripton":"Order via Prescripton",
         "Place an order":"Place an Order",
         "Your Pills for today":"Your Pills for today",
         "Add Reminder":"Add Reminder",

         //my account
         "Confirm":"Confirm",
         "Cancel":"Cancel",
         "MyAccount":"MyAccount",
        "Orders":"Orders",
        "Near Pharmacies":"Near Pharmacies",
        "Home":"Home",
        "Home ":"Home ",
           "Tap to Accept or refuse":"Tap to Accept or refuse",

            "Personal Information":"Personal Information",
        "Payment methods":"Payment methods",
        "Payment Method :":"Payment Method :",
        "Billing Address": "Billing Address",
        "Help and Support":"Help and Support",
        "Logout":"Logout",
        "Languages":"Languages",
        "Personal Data":"Personal Data",
        "Name":"Name",
        "Gender":"Gender",
        "Birthday":"Birthday",
        "Tap to Set":"Tap to Set",
        "alert":"Alert",
        "Select Gender":"Select Gender",
        "Male":"Male",
        "Female":"Female",
        "Save":"Save",
        "Default Language":"Default Language",
        "My Address":"My Address",
        "Work":"Work",
        "Delete":"Delete",
        "Edit":"Edit",
        "Street Name":"Street Name",
        "floor":"floor",
        "Apartment Number":"Apartment Number",
        "Add A New Address":"Add A New Address",
        "Default":"Default",
        "Long Press":"Long Press",
        "Long Press On Address to Change Default Address":"Long Press On Address to Change Default Address",
         "Changed Address":"Changed Address",
        "Changed Default Address to":"Changed Default Address to",
        "Nearby Pharmacies":"Nearby Pharmacies",
        "Nearby":"Nearby",
      "Distance":"Distance",
      "KM":"KM",
      "Deliver to ,":"Deliver to ,",
      "Pending":"Pending",
      "Completed":"Completed",
      "Waiting For Delivery":"Waiting For Delivery",
      "Delivered":"Delivered",
      "Pharmacy":"Pharmacy",
      "Try to create New orders":"Try to create New orders",
      "Delete Orders":"Delete Orders",
      "Are you sure to delete":"Are you sure to delete",
      "?":"?",
      "Rejected":"Rejected",
      "Delivering":"Delivering",
      "Medicine":"Medicine",
      "Price":"Price",
      "Order Date":"Order Date",
      "Order Details":"Order Details",
      "Tap to View Details":"Tap to View Details",
      "Try to Get Some Orders":"Try to Get Some Orders",

              //upload prescription page
    "Upload Prescription":"Upload Prescription",
    "Change":"Change",
    "Add Photos":"Add Photos",
    "Continue":"Continue",
    "Change Address":"Change Address",
    "Tap Here To Change Your Address":"Tap Here To Change Your Address",
     "Select Address to deliver": "Select Address to deliver",
     "Select":"Select",
     "Choose From":"Choose From",
     "Gallery":"Gellery",
     "Camera":"Camera",
     "Add Prescriptions":"Add Prescriptions",
     "Click Here To Attach Prescriptions ":"Click Here To Attach Prescriptions ",
      "No Pharmacies yet!!":"No Pharmacies yet!!",
        "Choose Pharmacies":"Choose Pharmacies",
     "Pick Distance to Show Pharmacies,":"Pick Distance to Show Pharmacies,",
     "Send to":"Send to",
     "Pharmacies":"Pharmacies",
     "No Pharmacies registered in this area try to scale KM":"No Pharmacies registered in this area try to scale KM",
     //Account Setting Screen
     "Change Language":"Change Language",
     "Change Default App Language":"Change Default App Language",
     "Try to Add your Default Address For Delivery":"Try to Add your Default Address For Delivery",
  //permission
  "GPS permission Request":"GPS permission Request",
  "Location permission is Required for better using of app":"Location permission is Required for better using of app",
  "Turn On Gps":"Turn On Gps",
    "Please Enable Gps And try Again...":"Please Enable Gps And try Again...",
    "GPS Error":"GPS Error",
  "Ok":"Ok",
    //add address
         "Additional Address Details":"Additional Address Details",
     "Address Label (Optional)":  "Address Label (Optional)",
  "SAVE ADDRESS":"SAVE ADDRESS",
  "Delete Address":"Delete Address",
  "Are you sure you want to delete this address":"Are you sure you want to delete this address",
  
  "Near to":"Near to",

  //prescriptions
  "Prescription":"Prescirption",
  //products
    "My Products":"My Products",
  "Add Product":"Add Product",
  "Add Product Image":"Add Product Image",
  "Prodcut Name":"Prodcut Name",
  "Product Price":"Product Price",
  "Product Category":"Product Category",
  "Capsules":"Capsules",
  "Syurp":"Syurp",
  "Other":"Other",
  "Baby":"Baby",
  "Cosmatics":"Cosmatics",
  "Discount Percentage (Optional)":"Discount Percentage (Optional)",
   "Edit Product":"Edit Product",
  "Edit Price":"Edit Price",
  "See All":"See All",
  "Please Add More Products":"Please Add More Products",
  
  //orders notification
  "New Order For You":"New Order For You",
  "Rejected Your Offer": "Rejected Your Offer",
  "Offer him a price":"Offer him a price",
  "Accept":"Accept",
  "Reject":"Reject",
  "Customer Name:":"Customer Name:",
  "accepted your offer":"accepted your offer",
  "View Order Details":"View Order Details",
  "Please Offer Him price for Prescription":"Please Offer Him price for Prescription",
  "Offer Accepted": "Offer Accepted",
  "Offer Rejected":"Offer Rejected",
  "Accepted Your Offer Deliver it now!!":"Accepted Your Offer Deliver it now!!",
  "Update":"Update",
  
     //snackbars
     "Error":"Error",
     "Please type in medicine":"Please type in medicine",
      "add pharmacies":"add pharmacies",
     "Please pick some Pharmacies":"Please pick some Pharmacies",
     "Sending Notification...":"Sending Notification...",
         "Pharmacy Order Rejected":"Pharmacy Order Rejected",
    "Rejected your Order":"Rejected your Order",
    "Order Accepted":"Order Accepted",
    "offers you":"offers you",
    "Tab To See":"Tab To See",
    "New Offer For Your Order": "New Offer For Your Order",
      "Loading...":"Loading...",
      "Too Late":"Too Late",
      "Customer Accepted Another Pharmacy Offer":"Customer Accepted Another Pharmacy Offer",
      "Pharmacy Offer":"Pharmacy Offer",
            "Great":"Great",
      "Succssefully Added Product":"Great",
      "fill fields":"fill fields",
      "Please Fill All Required Fields":"Please Fill All Required Fields",
     //add reminder
       
  "New Reminder":"New Reminder",
  "Medicine Name":"Medicine Name",
   "Type":"Type",
   " Time & Schedule ":" Time & Schedule ",
   "Duration":"Duration",
   "Once":"Once",
   "Repeated":"Repeated",
   " Repeat Every ":" Repeat Every ",
   "Type All Fields":"Type All Fields",
   "Please Fill in All Fields":"Please Fill in All Fields",
   "Add A Reminder":"Add A Reminder",
     //notification page
  "Notifications": "Notifications",
  "Order Number:":"Order Number:",
  "Order Request":"Order Request",
  "Tap To View":"Tap To View",
  " NOTE :":" NOTE :",
  "Give him a Call":"Give him a Call",
  "Start Chat with him":"Start Chat with him",

  //order from pharmacy
  "Make Order":"Make Order",
  "click on (Add Photos) to add Some Prescriptions of your medicine":"click on (Add Photos) to add Some Prescriptions of your medicine",
  "Please provide prescription photos or type in required medicine":"Please provide prescription photos or type in required medicine",
  "Address Is Empty":"Address Is Empty",
  "Please add at least one Address":"Please add at least one Address",
   "Submit":"Submit",

   //google map page
   "Locate Me":"Locate Me",
   "CONFIRM LOCATION":"CONFIRM LOCATION",
   //pharmacy details
   "Pharmacy Details":"Pharmacy Details",
   "Address":"Address",
   "Order Medicine":"Order Medicine",
   "Pharmacy Products":"Pharmacy Products",
  //PharmacyProducts
  "Products":"Products",
  "All":"All",
   

  
  "Pharmacy don't have any products till yet!!":"Pharmacy don't have any products till yet!!",
    //shopping cart 
  "Cart":"Cart",
  "Item":"Item",
  "Product Name: ":"Product Name: ",
  "Category: ":"Category: ",
  "L.E":"L.E",
  "CHECKOUT":"CHECKOUT",
  "Your Shopping Cart Is Empty":"Your Shopping Cart Is Empty",
  
    //order detail
  "Order Status :":"Order Status :",
      
          "Price :": "Price :",
"Set to Delivered":"Set to Delivered",
"In Cash":"In Cash",
      },
  
  };

}